stations = [
    '12th St. Oakland City Center',
    '16th St. Mission (SF)',
    '19th St. Oakland',
    '24th St. Mission (SF)',
    'Ashby (Berkeley)',
    'Balboa Park (SF)',
    'Bay Fair (San Leandro)',
    'Castro Valley',
    'Civic Center (SF)',
    'Coliseum/Oakland Airport',
    'Colma',
    'Concord',
    'Daly City',
    'Downtown Berkeley',
    'Dublin/Pleasanton',
    'El Cerrito del Norte',
    'El Cerrito Plaza',
    'Embarcadero (SF)',
    'Fremont',
    'Fruitvale (Oakland)',
    'Glen Park (SF)',
    'Hayward',
    'Lafayette',
    'Lake Merritt (Oakland)',
    'MacArthur (Oakland)',
    'Millbrae',
    'Montgomery St. (SF)',
    'North Berkeley',
    'North Concord/Martinez',
    'Orinda',
    'Pittsburg/Bay Point',
    'Pleasant Hill',
    'Powell St. (SF)',
    'Richmond',
    'Rockridge (Oakland)',
    'San Bruno',
    'San Francisco Int\'l Airport',
    'San Leandro',
    'South Hayward',
    'South San Francisco',
    'Union City',
    'Walnut Creek',
    'West Dublin',
    'West Oakland'
]
